title: Config
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: storiable_type
            field:
              options:
                -
                  key: company
                  value: Company
                -
                  key: department
                  value: Department
              inline: true
              type: radio
              display: Storiable
              instructions: 'Please select which type of storiable type you want to connect to.'
              validate:
                - required
          -
            handle: company_id
            field:
              max_items: 1
              mode: select
              type: yourstoryz_company
              display: Company
              instructions: 'Please select a company'
              if:
                storiable_type: 'equals company'
              validate:
                - 'required_if:storiable_type,company'
          -
            handle: department_id
            field:
              max_items: 1
              mode: select
              type: yourstoryz_department
              display: Department
              instructions: 'Please select a department'
              if:
                storiable_type: 'equals department'
              validate:
                - 'required_if:storiable_type,department'
          -
            handle: include_departments
            field:
              type: toggle
              display: 'Include departments stories'
              instructions: 'Include stories of the departments associated with this company.'
              if:
                storiable_type: 'equals company'
              always_save: true
